### ISSUE TITLE
data get_bars 2 minutes

### ISSUE THREAD

**Issue by ingelrii** [webull-inc/openapi-python-sdk#6]
Hello,

I need to run a program using your library, but I need the timespan for 2 minutes candles.

I can download bars for 1 minute or 5 minutes, but I don't find the way to download for 2 minutes.I s there any option to download them??

Thank you very much,

**Comment by EnigmaXyl** [comment]
@ingelrii Sorry, we will consider it later. But temporarily unable to support the timespan for 2 minutes

**Comment by ingelrii** [comment]
Thank you very much for your quick response. I hope it will be available soon.
